[tool.poetry]
name = "proustcli"
version = "0.1.0"
description = "A lightweight Lambda/API framework"
authors = ["JensRoland <mail@jensroland.com>"]
license = "MIT"
packages = [
    { include = "proustcli", from = "src" },
]

[tool.poetry.scripts]
proust = "proustcli.cli.__main__:proustcli"

[tool.poetry.dependencies]
aws-cdk-lib = "^2.67.0"
boto3 = "^1.17.113"
click = "^8.0.3"
constructs = ">=10.0.0,<11.0.0"
copier = "^6.2.0"  # 7.0.1 has a bug that deletes the template folder, see https://github.com/copier-org/copier/issues/1029
flask = "^2.1.0"
pyjwt = "^2.1.0"
python = "^3.9"
tomli = { version = "^2.0.1", python = "<3.11" }
xxhash = "^3.2.0"

[tool.poetry.group.dev.dependencies]
coverage = "^6.0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
