name: End To End test

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1

permissions:
  id-token: write   # This is required for requesting the JWT for AWS AssumeRole
  contents: read    # This is required for actions/checkout

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.9"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies (incl. dev)
        run: uv sync --all-extras --dev

      - name: Linting
        run: make lint

  e2e-uv:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::315498636918:role/kegstand-e2e-test-role
          role-session-name: Kegstand-E2E-test-${{ matrix.python-version }}

      - name: Install CDK CLI
        run: npm install -g aws-cdk

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.9"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (incl. the CLI itself)
        run: uv sync --all-extras

      - name: Create temporary project
        run: make e2e-create-project

      - name: Build project
        run: make e2e-build

      - name: Deploy project
        run: make e2e-deploy

      - name: Test endpoint
        run: make e2e-test

      - name: Teardown project
        run: make e2e-teardown
